version: '3.3'
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    command: sh /home/start.sh
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/html
    ports:
      - 80:80
    networks:
      default:      
        ipv4_address: 192.168.0.2
  php:
   build:
     context: ./php
     dockerfile: Dockerfile
   volumes:
     - ./app:/var/www/html
   command: sh /home/start.sh
   networks:
     default:      
       ipv4_address: 192.168.0.3
  #db:
  #   build:
  #     context: ./mysql
  #     dockerfile: Dockerfile
  #   ports:
  #     - 3306:3306
  #   volumes:
  #     - ./data:/var/lib/mysql
  #   command: sh /home/start.sh
  #   networks:
  #    default:      
  #      ipv4_address: 10.5.0.7
networks:
  default:
    external:
      name: dockernet