version: '3.3'
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    command: sh /home/start.sh
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/html
    ports:
      - 80:80
  php:
   build:
     context: ./php
     dockerfile: Dockerfile
   volumes:
     - ./app:/var/www/html
   command: sh /home/start.sh
  nodejs:
    build:
      context: ./nodejs
      dockerfile: Dockerfile
    command: sh /home/start.sh
    volumes:
      - ./src:/home/app
networks:
  default:
    external:
      name: dockernet